/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package huffman;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.PriorityQueue;
import javax.swing.JOptionPane;

/**
 *
 * @author arturs vitolins
 */
public class HuffmanMain extends javax.swing.JFrame {

    /**
     * Creates new form HuffmanMain
     */
    public HuffmanMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        compressButton = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        decompressButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        compressButton.setText("Arhivēt Failu");
        compressButton.setName(""); // NOI18N
        compressButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compressButtonActionPerformed(evt);
            }
        });

        jTextField1.setEnabled(false);

        decompressButton.setText("Atarhivēt failu");
        decompressButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decompressButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(compressButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(decompressButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(decompressButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(compressButton)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void decompressButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decompressButtonActionPerformed
        String encodedFilePath = "./test-encoded.txt";

        StringBuilder encodedFileContentBuilder = new StringBuilder();
        FileUtils.readFileIntoStringBuild(encodedFileContentBuilder, encodedFilePath);

        String encodedFileContent = encodedFileContentBuilder.toString();
        int substringStartOffset = 1;
        int indexOfEncodingTableStart = encodedFileContent.indexOf("{");
        int indexOfEncodingTableEnd = encodedFileContent.indexOf("}");
        String encodingTableString = encodedFileContent.substring(indexOfEncodingTableStart+ substringStartOffset, indexOfEncodingTableEnd);

        Map<String, Character> encodingMap = HuffmanUtils.buildEncodingMapFromFile(encodingTableString);
        System.out.println(encodingMap.toString());

        String encodedContent = encodedFileContent.substring(indexOfEncodingTableEnd + substringStartOffset);
        encodedContent = HuffmanUtils.byteContentToStringBytes(encodedContent, encodingMap);

        System.out.println("decoding-start");
        String decodedText = HuffmanUtils.decodeFileContent(encodedContent, encodingMap);
        System.out.println("decoding-end");

        File decodedFile = new File("./test-decoded.txt");
        try ( FileWriter myWriter = new FileWriter(decodedFile)) {
            myWriter.write(decodedText);
            
            String successMsg = "CREATED DECODED FILE SUCCESFULLY\n"+decodedFile.getCanonicalPath();
            JOptionPane.showMessageDialog(this, successMsg);
            System.out.println(successMsg);
        } catch (Exception ex) {
            ex.printStackTrace();
        }


    }//GEN-LAST:event_decompressButtonActionPerformed

    private void compressButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compressButtonActionPerformed
        String filePath = jTextField1.getText();
        filePath = "./test.txt";

        Map<String, Integer> table = HuffmanUtils.buildFrequencyTable(filePath);

        System.out.println(table);

        PriorityQueue<HuffmanNode> queue = HuffmanUtils.buildPriorityQueue(table);

        HuffmanNode root = HuffmanUtils.buildEncodingTree(queue);

        Map<Character, String> codeMap = new HashMap<>();
        HuffmanUtils.buildEncodingMap(root, "", codeMap);

        System.out.println(codeMap);

        File encodedFile = new File("./test-encoded.txt");
        try (FileWriter myWriter = new FileWriter(encodedFile)) {
            StringBuilder fileContent = new StringBuilder();
            FileUtils.readFileIntoStringBuild(fileContent, filePath);

            String encodedString = HuffmanUtils.encodeFileContentByCodeMap(fileContent, codeMap);

            HuffmanUtils.writeCodeMapToFile(myWriter, codeMap);
            HuffmanUtils.writeEncodedStringToFile(myWriter, encodedString);

            String successMsg = "ENCODED FILE SUCCESSFULLY\n"+encodedFile.getCanonicalPath();
            JOptionPane.showMessageDialog(this, successMsg);
            System.out.println(successMsg);
            
        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_compressButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HuffmanMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HuffmanMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HuffmanMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HuffmanMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HuffmanMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton compressButton;
    private javax.swing.JButton decompressButton;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
